include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "daty-git.flatpak"
    GIT_SUBMODULE_STRATEGY: recursive

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "flatpak/ml.prevete.DatyNightly.json"
        FLATPAK_MODULE: "daty"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "ml.prevete.Daty"
    extends: .flatpak
