name: daty
version: git
summary: Daty Wikidata Editor
description: |
  Daty is a free Wikidata editor adhering to GNOME Human Interface Guidelines,
  intended to enable a better editing workflow and faster deployment of requested user features for Wikidata.
  Use Daty to search, select, read, batch edit items, script actions, share, visualize proposed changes and bots.

confinement: devmode
base: core18

parts:
  daty:
    build-packages:
      - libgirepository1.0-dev
      - libcairo2-dev
      - pkg-config
      - python3-cairo-dev
      - python3-gi
      - python3-cairo
    build-snaps:
      - libhandy
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      #- libcairo2
      #- python3-cairo
      #- python3-gi
      - python3-six

apps:
  daty:
    command: bin/daty
